update web-build

diff --git a/web-build b/web-build
--- a/web-build
+++ b/web-build
@@ -1,9 +1,33 @@
 #!/bin/bash
 
 rl_dir="/home/akos/raylib"
+dev_dir="./web"
+prod_dir="/home/akos/repos/magyarakoos.github.io/minesweeper"
+
+# Check if there is exactly one argument
+if [ "$#" -ne 1 ]; then
+    echo "Usage: $0 <dev/prod>"
+    exit 1
+fi
+
+# Check the argument value
+case "$1" in
+    "dev")
+        output_dir="$dev_dir"
+        ;;
+    "prod")
+        output_dir="$prod_dir"
+        
+        cp "$dev_dir/minesweeper.html" "$prod_dir/"
+        ;;
+    *)
+        echo "Invalid argument. Exiting."
+        exit 1
+        ;;
+esac
 
 emcc -o \
-    ./web/shell.html \
+    "$output_dir/shell.html" \
     src/*.cpp \
     -Wall \
     -std=c++17 \
@@ -12,17 +36,17 @@ emcc -o \
     -Wunused-result \
     -Os \
     -I. \
-    -I $rl_dir/src \
-    -I $rl_dir/src/external \
+    -I "$rl_dir/src" \
+    -I "$rl_dir/src/external" \
     -L. \
-    -L $rl_dir/src \
+    -L "$rl_dir/src" \
     -s USE_GLFW=3 \
     -s ASYNCIFY \
     -s TOTAL_MEMORY=67108864 \
     -s FORCE_FILESYSTEM=1 \
     --preload-file assets \
     --shell-file shell.html \
-    $rl_dir/src/libraylib.a \
+    "$rl_dir/src/libraylib.a" \
     -DPLATFORM_WEB \
     -s 'EXPORTED_FUNCTIONS=["_free","_malloc","_main"]' \
     -s EXPORTED_RUNTIME_METHODS=ccall
